import { PAGE_SECTIONS } from '../shared/settings'
import { BLOCKED_SECTION_ATTRS, SECTION_SELECTORS } from './selectors'

/**
 * Set on `<html>` once the content script has read settings and applied them.
 * Its absence means "not decided yet", never "nothing is blocked", which is why
 * teardown sets it rather than clearing it: an unloaded extension must not
 * leave the page hidden.
 */
export const READY_ATTR = 'data-igfb-ready'

/**
 * How long the curtain hides its targets when nothing ever clears the gate.
 * The content script normally clears it within milliseconds; this is the
 * backstop for the case where its JavaScript never runs at all.
 *
 * `display: none` cannot be lifted by an animation, which is why the curtain is
 * `content-visibility` plus `visibility` instead. `content-visibility`
 * collapses a container's contents but not a replaced element, and
 * `visibility` hides the replaced element but keeps its space, so the pair
 * covers both and both can be animated back.
 */
export const CURTAIN_EXPIRY_MS = 4000

/**
 * The content script's own backstop, well under the stylesheet's, so recovery
 * from a storage read that never returns is a JavaScript one and the CSS
 * expiry stays the last resort.
 */
export const READY_FALLBACK_MS = 1500

const LIFT_ANIMATION = 'igfb-curtain-lift'

/**
 * Every section's selectors, deduplicated. The curtain cannot be route-scoped:
 * CSS cannot see the URL, and manifest `matches` are not re-evaluated when
 * Instagram navigates client-side. So it covers the union, which includes
 * `main` itself for Reels. That is safe only because the gate clears before
 * Instagram renders anything, and because the rule expires on its own.
 */
export const getCurtainSelectors = () => {
  return Array.from(
    new Set(PAGE_SECTIONS.flatMap(section => SECTION_SELECTORS[section])),
  )
}

const sectionRule = (section: (typeof PAGE_SECTIONS)[number]) => {
  const attribute = BLOCKED_SECTION_ATTRS[section]
  const selectors = SECTION_SELECTORS[section]
    .map(selector => `html[${attribute}] ${selector}`)
    .join(',\n')

  // `!important` because Instagram's own rules are author origin too. An
  // inline `display` set by Instagram would still win, silently, so that is
  // the first thing to check if a section ever stops hiding.
  return `${selectors} {\n  display: none !important;\n}`
}

export const buildBlockingCss = () => {
  const curtain = getCurtainSelectors()
    .map(selector => `html:not([${READY_ATTR}]) ${selector}`)
    .join(',\n')

  return `/*
 * Generated by src/content/blockingStyles.ts. Do not edit.
 * Run UPDATE_BLOCKING_CSS=1 pnpm test to regenerate.
 *
 * Declared at document_start for every Instagram page, so the rules exist
 * before anything renders and apply to whatever Instagram mounts later, on any
 * route, without a re-query.
 *
 * The first rule is the curtain: until the content script marks the page
 * ready, every target of every section is hidden, because nothing knows which
 * sections are blocked before the settings read lands. Its animation is a
 * backstop, not decoration: if the content script never runs, the curtain
 * lifts itself instead of leaving Instagram blank.
 *
 * The rest hide a section while its attribute is set on <html>.
 */

@keyframes ${LIFT_ANIMATION} {
  to {
    content-visibility: visible;
    visibility: visible;
  }
}

${curtain} {
  content-visibility: hidden;
  visibility: hidden;
  animation: 0s linear ${CURTAIN_EXPIRY_MS}ms forwards ${LIFT_ANIMATION};
}

${PAGE_SECTIONS.map(sectionRule).join('\n\n')}
`
}

/**
 * One-way on purpose: see `READY_ATTR`.
 */
export const markBlockingReady = () => {
  document.documentElement.setAttribute(READY_ATTR, 'true')
}

export const isBlockingReady = () => {
  return document.documentElement.hasAttribute(READY_ATTR)
}
